# Generated by Django 4.1.7 on 2023-03-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='color',
            field=models.CharField(default='Blue', max_length=10),
        ),
        migrations.AddField(
            model_name='toy',
            name='name',
            field=models.CharField(default='Rick', max_length=50),
        ),
    ]
