# Generated by Django 4.1.7 on 2023-03-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_toy_color_toy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='toy',
            name='name',
            field=models.CharField(default='Nobody', max_length=50),
        ),
    ]
