# Generated by Django 4.1.7 on 2023-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_toy_color_alter_toy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
