# Generated by Django 4.1.7 on 2023-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_toy_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
